In [7]:
import numpy as np

a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [10]:
mean_a = np.mean(a, axis=0)
print(mean_a)


[2.  8.4]


In [11]:
a_centered = a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [28]:
A = a_centered[:, 0]
B = a_centered[:, 1]
a_centered_sp = A@B
print(a_centered_sp)
N = A.size
cov = a_centered_sp/(N-1)
print(cov)

8.0
2.0


In [36]:
a_t = np.transpose(a)
np.cov(a_t)

array([[1. , 2. ],
       [2. , 4.3]])