In [486]:
import numpy as np

In [487]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [488]:
aa = a.reshape(2,6)
print(aa)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [489]:
aa = a.reshape(3,4)
print(aa)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [490]:
aa = a.reshape(4,3)
print(aa)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [491]:
aa = a.reshape(6,2)
print(aa)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [492]:
aa = a.reshape(12,1)
print(aa)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [493]:
aa = a.reshape(-1,6)
print(aa)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [494]:
aa = a.reshape(-1,3)
print(aa)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [495]:
aa = a.reshape(12,-1)
print(aa)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [496]:
aa = a.reshape(4,-1)
print(aa)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [497]:
aa = a.reshape(6,-1)
print(aa)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


### Массив Numpy, состоящий из одного столбца и 12 строк нельзя  назвать одномерным, потому что у одномерного массива может быть только одна строка.

In [498]:
a = np.random.randn(3, 4)
print(a.size)
print(a.shape)
print(a)
b = a.flatten()
print(b.size)
print(b.shape)
print(b)

12
(3, 4)
[[ 0.81363846  0.95168264 -1.02251819 -0.04187409]
 [-0.70158795  2.18128792  1.03482808 -0.49354599]
 [-0.01395411 -0.45548527  0.29257232 -1.25854745]]
12
(12,)
[ 0.81363846  0.95168264 -1.02251819 -0.04187409 -0.70158795  2.18128792
  1.03482808 -0.49354599 -0.01395411 -0.45548527  0.29257232 -1.25854745]


In [499]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [500]:
b = np.arange(19, 0, -2).reshape(10,1)
print(b)

[[19]
 [17]
 [15]
 [13]
 [11]
 [ 9]
 [ 7]
 [ 5]
 [ 3]
 [ 1]]


### Разница между массивами a и b в том, что a - одномерный массив, а b - нет.

In [501]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
print(a)
print(b)
v = np.vstack((a, b))
print('-'*25)
print(v)
print(v.size)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
-------------------------
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


In [502]:
a = np.arange(1,13)
print(a)
A = a.reshape(4,3)
print(A)
At = np.transpose(A)
print(At)
B = A.dot(At)
print(B)
print(B.size)
d = np.linalg.det(B)
print(d)
print('Мы можем посчитать обратную матрицу, т.к. определитель не равен 0')

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]
16
7.446513419535917e-28
Мы можем посчитать обратную матрицу, т.к. определитель не равен 0


In [503]:
import random
random.seed(42)
print(random.random())

0.6394267984578837


In [504]:
c = np.random.randint(0, 16, (1, 16))
c = c.flatten()
print(c)

[ 5  8  9 15  3  4  1  7  5 11 10 15  2 11  4  0]


In [505]:
C = c.reshape(4,4)
print(C)

[[ 5  8  9 15]
 [ 3  4  1  7]
 [ 5 11 10 15]
 [ 2 11  4  0]]


In [506]:
D=(C*10)+B
print(D)

[[ 64 112 140 218]
 [ 62 117 132 237]
 [100 232 294 416]
 [ 88 277 306 365]]


In [507]:
print(np.linalg.det(D))
print(np.linalg.matrix_rank(B))
D_inv = np.linalg.inv(D)
print(D_inv)

-7873800.000000006
2
[[ 0.09921512 -0.03027509 -0.04060809  0.00668292]
 [-0.01325154  0.02962737 -0.02573599  0.01800909]
 [ 0.0197211  -0.04512688  0.02129848 -0.0067515 ]
 [-0.03039701  0.02264726  0.01146587 -0.00687851]]


In [508]:
D_inv = np.where(D_inv < 0.0, D_inv, 1)
D_inv = np.where(D_inv > 0.0, D_inv, 0)
print(D_inv)

[[1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 1. 0.]]


In [509]:
ind1 = D_inv == 1
print(B)
print(B[ind1])
x=(B[ind1]).reshape(-1,4)
print(x)

[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]
[ 14  68  77 167  50 194 167 266]
[[ 14  68  77 167]
 [ 50 194 167 266]]


In [510]:
ind2 = D_inv == 0
print(C)
print(C[ind2])
y=(C[ind2]).reshape(-1,4)

[[ 5  8  9 15]
 [ 3  4  1  7]
 [ 5 11 10 15]
 [ 2 11  4  0]]
[ 8  9  3  1 11 15  2  0]


In [517]:
print(x)
print(y)
E = np.vstack((x, y))
print(E)

[[ 14  68  77 167]
 [ 50 194 167 266]]
[[ 8  9  3  1]
 [11 15  2  0]]
[[ 14  68  77 167]
 [ 50 194 167 266]
 [  8   9   3   1]
 [ 11  15   2   0]]
