In [1]:
import numpy as np

In [6]:
a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [10]:
aa = a.reshape(2,6)
print(aa)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [11]:
aa = a.reshape(3,4)
print(aa)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [12]:
aa = a.reshape(4,3)
print(aa)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [14]:
aa = a.reshape(6,2)
print(aa)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [15]:
aa = a.reshape(12,1)
print(aa)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [16]:
aa = a.reshape(-1,6)
print(aa)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [17]:
aa = a.reshape(-1,3)
print(aa)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [19]:
aa = a.reshape(12,-1)
print(aa)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [21]:
aa = a.reshape(4,-1)
print(aa)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [22]:
aa = a.reshape(6,-1)
print(aa)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


### Массив Numpy, состоящий из одного столбца и 12 строк нельзя  назвать одномерным, потому что у одномерного массива может быть только одна строка.

In [60]:
a = np.random.randn(3, 4)
print(a.size)
print(a.shape)
print(a)
b = a.flatten()
print(b.size)
print(b.shape)
print(b)

12
(3, 4)
[[ 0.88853072 -0.86957595 -0.75669241  0.46773752]
 [-0.21944193 -0.60271086 -1.54939877  0.26095544]
 [ 0.91632754 -0.25126568  0.81679411 -0.72398036]]
12
(12,)
[ 0.88853072 -0.86957595 -0.75669241  0.46773752 -0.21944193 -0.60271086
 -1.54939877  0.26095544  0.91632754 -0.25126568  0.81679411 -0.72398036]


In [27]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [37]:
b = np.arange(19, 0, -2).reshape(10,1)
print(b)

[[19]
 [17]
 [15]
 [13]
 [11]
 [ 9]
 [ 7]
 [ 5]
 [ 3]
 [ 1]]


### Разница между массивами a и b в том, что a - одномерный массив, а b - нет.

In [66]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
print(a)
print(b)
v = np.vstack((a, b))
print('-'*25)
print(v)
print(v.size)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
-------------------------
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


In [89]:
a = np.arange(1,13)
print(a)
A = a.reshape(4,3)
print(A)
At = np.transpose(A)
print(At)
B = A.dot(At)
print(B)
print(B.size)
d = np.linalg.det(B)
print(d)
print('Мы можем посчитать обратную матрицу, т.к. определитель не равен 0')

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 14  32  50  68]
 [ 32  77 122 167]
 [ 50 122 194 266]
 [ 68 167 266 365]]
16
7.446513419535917e-28
Мы можем посчитать обратную матрицу, т.к. определитель не равен 0


In [93]:
import random
random.seed(42)
print(random.random())

0.6394267984578837


In [105]:
c = np.random.randint(0, 16, (1, 16))
c = c.flatten()
print(c)

[13  1  9 12 12 10  3  8 12  3  2  8 15 15 12  5]


In [107]:
C = c.reshape(4,4)
print(C)

[[13  1  9 12]
 [12 10  3  8]
 [12  3  2  8]
 [15 15 12  5]]


In [108]:
D=(C*10)+B
print(D)

[[144  42 140 188]
 [152 177 152 247]
 [170 152 214 346]
 [218 317 386 415]]


In [129]:
print(np.linalg.det(D))
print(np.linalg.matrix_rank(B))
D_inv = np.linalg.inv(D)
print(D_inv)

-241834400.00000066
2
[[ 0.01282092  0.01208157 -0.01285632 -0.00227999]
 [-0.00568505  0.00907447 -0.00470454  0.00109678]
 [ 0.00452318 -0.01076795 -0.00297336  0.00683881]
 [-0.00659939 -0.00326256  0.01311261 -0.00359138]]


In [130]:
D_inv = np.where(D_inv < 0.0, D_inv, 1)
D_inv = np.where(D_inv > 0.0, D_inv, 0)
print(D_inv)

[[1. 1. 0. 0.]
 [0. 1. 0. 1.]
 [1. 0. 0. 1.]
 [0. 0. 1. 0.]]


### Объединить массивы по маске сообразить не получилось.